# Generated by Django 5.0.6 on 2024-06-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigIntegerField(blank=True, default='id', primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='country')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='state')),
                ('county', models.CharField(blank=True, max_length=255, null=True, verbose_name='county')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('lat', models.FloatField(blank=True, max_length=255, verbose_name='lat')),
                ('lng', models.FloatField(blank=True, max_length=255, null=True, verbose_name='lng')),
            ],
        ),
    ]
