# Generated by Django 5.0.6 on 2024-07-13 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherAppModule', '0002_toggle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toggle',
            new_name='Toggle_Standard',
        ),
    ]
